"""
Some functions to evaluate the wave patterns in the free atmosphere.
"""

__author__ = "Koen Devesse"
__date__ = "December 17, 2021"

from cmath import sqrt
import numpy as np
from numba import njit
import numba
import wayve.pressure.gravity_waves.nonuniform_methods as nus


def get_du_field(eta_t, z, grid, abl, gw):
    """
    Return the velocity field (total magnitude) in the free atmosphere.
    """
    # Get background velocity
    S = np.sqrt(abl.u(z)**2 + abl.v(z)**2)
    # Get pressure
    dp = get_dp_field(eta_t, z, grid, abl, gw)
    # Get velocity
    du = np.zeros(dp.shape)
    Nz = len(z)
    for i in range(Nz):
        du[:, :, i] = - dp[:, :, i] / S[i]
    return du


def get_dp_field(eta_t, z, grid, abl, gw):
    """
    Return the pressure perturbation in the free atmosphere.
    """
    conversion = p_per_w(z, grid, abl, gw)
    return get_wave_field(eta_t, z, grid, abl, gw, conversion)


def get_w_field(eta_t, z, grid, abl, gw):
    """
    Return the vertical velocity perturbation in the free atmosphere.
    """
    Nx = grid.Nx2
    Ny = grid.Ny
    Nz = len(z)
    conversion = np.ones([Nx, Ny, 2*Nz])
    return get_wave_field(eta_t, z, grid, abl, gw, conversion)


def get_eta_field(eta_t, z, grid, abl, gw):
    """
    Return the eta perturbation in the free atmosphere.
    """
    conversion = eta_per_w(z, grid, abl)
    return get_wave_field(eta_t, z, grid, abl, gw, conversion)


def get_wave_field(eta_t, z, grid, abl, gw, conversion):
    """
    Return the wave field generated by the lower boundary displacement eta_t.

    Parameters
    ----------
    eta_t   Lower level displacement
    kv  Wave-numbers in x-direction
    lv  Wave-numbers in x-direction
    z   Altitude array
    abl     ABL object
    gw      GravityWaves object
    conversion  Function to convert to wanted parameter (more information below)
    """
    # Get grid information
    kv = grid.ks2
    lv = grid.ls
    # Get wave amplitudes
    # Get piecewise constant method inputs
    N_param, u_param, v_param, d2u_param, d2v_param, h_int, u_int, v_int, du_int, dv_int = gw.pcm_input_setup(abl)
    h_interfaces, m_squared, amps = gw.get_waves(abl, kv, lv)
    # Atmospheric inputs
    u = abl.u(z)
    v = abl.v(z)
    u_0 = u_int[0]
    v_0 = v_int[0]
    # Set up wave field (in Fourier space)
    wave_f = get_wave_at_h(eta_t, kv, lv, z, conversion, u, v, u_0, v_0, m_squared, amps, h_interfaces)
    # Transform to real space in x,y
    wave = ifft(wave_f, grid)
    return wave


@njit(parallel=False)
def get_wave_at_h(eta_t, kv, lv, z, conversion, u, v, u_0, v_0, m_squared, amps, h_interfaces):
    # Set up wave field (in Fourier space)
    Nx = len(kv)
    Ny = len(lv)
    Nz = len(z)
    wave_f = np.zeros((Nx, Ny, Nz), dtype=np.complex128)
    # Loop over k, l
    for indexk in numba.prange(Nx):
        for indexl in numba.prange(Ny):
            k = kv[indexk]
            l = lv[indexl]
            omega_0 = -(u_0 * k + v_0 * l)
            if not omega_0 == 0.:
                m2 = m_squared[indexk, indexl]
                # Scale amplitudes with vertical velocity at lower boundary
                scale = (-1.j * omega_0) * eta_t[indexk, indexl]
                amps_scaled = scale * amps[indexk, indexl, :]
                # Calculate wave variable at specified altitudes (real in z)
                layer_index = 0
                for indexh in numba.prange(Nz):
                    h = z[indexh]
                    omega = -(u[indexh] * k + v[indexh] * l)
                    if not omega == 0.:
                        while layer_index < len(h_interfaces) - 1 and h > h_interfaces[layer_index + 1]:
                            layer_index += 1
                            if layer_index == len(h_interfaces) - 1:
                                break
                        # Convert amplitudes
                        amps_conv_p = amps_scaled[2*layer_index] * conversion[indexk, indexl, 2*indexh]
                        amps_conv_m = amps_scaled[2*layer_index+1] * conversion[indexk, indexl, 2*indexh+1]
                        # Evaluate wave at altitude
                        wave_f[indexk, indexl, indexh] = get_wave_from_amps(amps_conv_p, amps_conv_m,
                                                                            m2[layer_index], h - h_interfaces[layer_index])
                    else:
                        break
    return wave_f


@njit(parallel=False)
def get_wave_from_amps(A_p, A_m, m2, dh):
    p_contr = 0.
    m_contr = 0.
    if A_p != 0.:
        p_contr = A_p * np.exp(1j * sqrt(m2) * dh)
    if A_m != 0.:
        m_contr = A_m * np.exp(-1j * sqrt(m2) * dh)
    W = p_contr + m_contr
    return W


def ifft(wave_f, grid):
    Nx = grid.Nx
    Ny = grid.Ny
    Nz = wave_f.shape[2]
    wave = np.zeros((Nx, Ny, Nz))
    # Transform to real space in x,y
    for i in range(Nz):
        wave[:, :, i] = grid.c2r(wave_f[:, :, i])
    return wave


# #######################################
# ########## CONVERSION SETUPS ##########
# #######################################
#
# All the below functions are used to convert the wave information computed by the piecewise method, which is
# re-structured as the up- and down-going wave amplitudes of the vertical displacement, to other wave parameters.
# Specifically, for each altitude the parameter is to be computed for, they output the two scalars per wavenumber that
# the vertical velocity amplitudes have to be multiplied with to obtain the desired perturbation property.
# As an example: eta_per_w computes 1j/omega at every altitude for all amplitudes, as multiplying W_+ and W_- with this
# transforms the vertical velocity amplitudes to vertical displacement amplitudes. For pressure, the conversions are
# based on eq. 19 of Devesse et al., 2022 (https://doi.org/10.5194/wes-7-1367-2022).

def eta_per_w(z, grid, abl):
    # Get grid information
    kv = grid.ks2
    lv = grid.ls
    Nx = len(kv)
    Ny = len(lv)
    Nz = len(z)
    # Set up atmospheric variables
    u = abl.u(z)
    v = abl.v(z)
    # Set up convective derivatives
    conv = np.zeros((Nx, Ny, 2*Nz), dtype=np.complex128)
    # Loop over k, l
    for indexk in numba.prange(Nx):
        for indexl in numba.prange(Ny):
            k = kv[indexk]
            l = lv[indexl]
            for i in numba.prange(Nz):
                omega = -(u[i] * k + v[i] * l)
                if not np.abs(omega) == 0.:
                    conv[indexk, indexl, 2*i] = 1.j / omega
                    conv[indexk, indexl, 2*i+1] = 1.j / omega
                else:
                    break
    return conv


def p_per_w(z, grid, abl, gw):
    # Get grid information
    kv = grid.ks2
    lv = grid.ls
    Nx = len(kv)
    Ny = len(lv)
    Nz = len(z)
    # Get piecewise constant method inputs
    N_param, u_param, v_param, d2u_param, d2v_param, h_int, u_int, v_int, du_int, dv_int = gw.pcm_input_setup(abl)
    # Set up atmospheric variables
    u = abl.u(z)
    v = abl.v(z)
    du = np.gradient(u, z)
    dv = np.gradient(v, z)
    u_0 = u_int[0]
    v_0 = v_int[0]
    # Set up conversion matrix
    conv = np.zeros([Nx, Ny, 2*Nz], dtype=np.complex128)
    p_conv_setup(conv, z, Nx, Ny, Nz, kv, lv,
                 u, v, du, dv, u_0, v_0,
                 N_param, u_param, v_param, d2u_param, d2v_param,
                 h_int)
    return conv


@njit(parallel=False)
def p_conv_setup(conv, z, Nx, Ny, Nz, kv, lv,
                 u, v, du, dv, u_0, v_0,
                 N_param, u_param, v_param, d2u_param, d2v_param,
                 h_interfaces):
    # Loop over k, l
    for indexk in numba.prange(Nx):
        for indexl in numba.prange(Ny):
            k = kv[indexk]
            l = lv[indexl]
            omega_0 = -(u_0*k + v_0*l)
            if not omega_0 == 0.:
                m2 = nus.m_squared(N_param, u_param, v_param, d2u_param, d2v_param, k, l)
                layer_index = 0
                for indexh in numba.prange(Nz):
                    h = z[indexh]
                    while layer_index < len(h_interfaces) - 1 and h > h_interfaces[layer_index + 1]:
                        layer_index += 1
                        if layer_index == len(h_interfaces) - 1:
                            break
                    omega_i = -(u[indexh]*k + v[indexh]*l)
                    domegadz_i = -(du[indexh]*k + dv[indexh]*l)
                    # omega_i = -(u_param[layer_index]*k + v_param[layer_index]*l)
                    # domegadz_i = -(du_param[layer_index]*k + dv_param[layer_index]*l)
                    m_i = sqrt(m2[layer_index])
                    conv[indexk, indexl, 2*indexh] = (-omega_i*m_i - 1.j*domegadz_i) / (k**2 + l**2)
                    conv[indexk, indexl, 2*indexh+1] = (omega_i*m_i - 1.j*domegadz_i) / (k**2 + l**2)
    return conv