#!/usr/bin/env python

"""
Script demonstrating the inclusion of topography.

References
----------
..  Allaerts, D., & Meyers, J. (2019). Sensitivity and feedback of wind-farm-induced gravity waves. Journal of Fluid
 Mechanics, 862, 990–1028. https://doi.org/10.1017/jfm.2018.969
"""
__author__ = "Koen Devesse"
__date__ = "January 17, 2020"

import numpy as np
import matplotlib.pyplot as plt

from wayve.apm import APM
from wayve.abl.abl_setup import AM2019
from wayve.grid.grid import Stat2Dgrid
from wayve.forcing.pressure_forcing import topography
from wayve.momentum_flux_parametrizations import FrictionCoefficients
from wayve.pressure.gravity_waves.gravity_waves import Uniform
from wayve.solvers import NoFeedback
from wayve.pressure.gravity_waves.wave_patterns import get_du_field, get_dp_field
from examples.plotting import apm_plot, plot_field


# ----------------------------------------------- #
# --------- Step 1: define topography ----------- #
# ----------------------------------------------- #

# Topography is included in the APM as additional pressure gradients due to the displacement of the capping inversion.
# Users can use commonly used pre-defined shapes, such as a Gaussian hill or a Witch of Agnesi profile. In this example,
# we use a Gaussian hill.

# Hill shape
h_hill = 50.
L_hill = 10.e3
W_hill = 20.e3

# Hill center location (at grid center)
x_c = 0.
y_c = 0.

# Generate Topography object
hill = topography.GaussianHill(h_hill, L_hill, W_hill, x_c, y_c)


# ------------------------------------------------ #
# -------------- Step 2: set up APM -------------- #
# ------------------------------------------------ #

# Use the atmospheric conditions from the example of Allaerts and Meyers (2019).
sub = True      # Sub- or supercritical case
abl = AM2019(sub)

# Generate 2D grid object
Nx = 2000           # grid points in x-direction
Lx = 1.e6           # grid size in x-direction [m]
Ny = 800            # grid points in y-direction
Ly = 0.4e6          # grid size in y-direction [m]
grid = Stat2Dgrid(Lx, Nx, Ly, Ny)

# Momentum flux parametrization
mfp = FrictionCoefficients()

# Pressure feedback parametrization
pressure = Uniform(dynamic=True, rotating=False)

# Create static 2D model
model = APM(grid, hill, abl, mfp, pressure)


# ------------------------------------------------- #
# ------------- Step 3: solve the APM ------------- #
# ------------------------------------------------- #

# Since the pressure perturbation generated by the topography does not depend on the APM state, there are no higher
# order terms, and the APM equations decouple per wave-number. We can therefore simply use a direct matrix solve.
solver = NoFeedback()

# Solve linear system
result = model.solve(method=solver, verbose=True)


# ------------------------------------------------------ #
# ------------ Some example post processing ------------ #
# ------------------------------------------------------ #

# Difference in velocity magnitude in wind-farm layer
M1 = -(abl.S1-np.sqrt((abl.U1+result['u1r'])**2 +
                      (abl.V1+result['v1r'])**2)) / abl.S1*100

# Difference in velocity magnitude in upper layer
M2 = -(abl.S2-np.sqrt((abl.U2+result['u2r'])**2 +
                      (abl.V2+result['v2r'])**2)) / abl.S2*100

# Field plots #
# Set up plot
f, axarr = plt.subplots(1, 3, figsize=(15., 5.))  # Make sure there is enough room for the colorbars
f.subplots_adjust(wspace=0.75)
# Plot boundaries (in km)
lim = 100.
x_lims = [-lim, lim]
y_lims = [-lim, lim]
# Plot variables
plot_field(result['etar'] / abl.H * 100, grid, r'$\eta_t/H\;[\%]$', axarr[0], f, x_lims, y_lims)
plot_field(result['pr'] / abl.S1 ** 2 * 100, grid, r'$p^\prime/\rho_0U_1^2\;[\%]$', axarr[1], f, x_lims, y_lims)
plot_field(M1, grid, r'$u^\prime_1/U_1\;[\%]$', axarr[2], f, x_lims, y_lims)
# Plot outline of forcing term #
# Hill profile on APM grid
h0 = hill.eta(grid)
# Select relevant part of the grid
select_x = np.logical_and(x_lims[0] <= grid.xs/1.e3, grid.xs/1.e3 <= x_lims[1])
select_y = np.logical_and(y_lims[0] <= grid.ys/1.e3, grid.ys/1.e3 <= y_lims[1])
for ax in axarr:
    n_cont = 3      # Number of contour lines
    ax.contour(grid.xs[select_x] / 1.0e3,
               grid.ys[select_y] / 1.0e3,
               np.transpose(h0[select_x][:, select_y]),
               levels=np.linspace(0., h_hill, n_cont+2),
               linestyles="dashed", colors="k")
# Show plot
plt.show()

# APM plots #
# Calculate gravity wave fields in the free atmosphere
Nz_upper = 100
z_upper = np.linspace(abl.H, 5.*abl.H, Nz_upper+1, endpoint=True)
print(f"Start calculations for gravity wave visualisation")
u_wave = get_du_field(result['etac'], z_upper, grid, abl, pressure) / abl.S3 * 100.
p_wave = get_dp_field(result['etac'], z_upper, grid, abl, pressure) / abl.S3**2*100.
print(f"Gravity wave calculations done")
# Combine variables into input lists
etas = [result['eta1r'], result['eta2r']]
u_fields = [M1*abl.S1/abl.S3, M2*abl.S2/abl.S3]
p_fields = [result['p1r']/abl.S3**2*100, result['p2r']/abl.S3**2*100]
# Velocity perturbation #
# Set up plot
f, ax = plt.subplots()
# Perform APM plot
im = apm_plot(u_fields, grid, abl, etas, u_wave, z_upper, ax, x_lims, eta_0=h0)
# Add colorbar
f.colorbar(im, ax=ax, shrink=1.0, label=r"$\Delta u/U_g$ [%]")
# Show plot
plt.show(block=False)
# Pressure perturbation #
# Set up plot
f, ax = plt.subplots()
# Perform APM plot
im = apm_plot(p_fields, grid, abl, etas, p_wave, z_upper, ax, x_lims, eta_0=h0)
# Add colorbar
f.colorbar(im, ax=ax, shrink=1.0, label=r'$p\prime/\rho_0U_g^2\;[\%]$')
# Show plot
plt.show()
